### ISSUE TITLE
Unparsed HTML elements on 'Scratch Paper' tab name

### ISSUE THREAD

**Issue by item4** [parkjs814/AlgorithmVisualizer#10]
<img width="605" alt="2016-05-23 2 33 05" src="https://cloud.githubusercontent.com/assets/559952/15455419/b737073c-208e-11e6-9d9c-6a6d74dee0f8.png">

OS: Mac OS X
Browser: Firefox 46.0.1

**Comment by parkjs814** [comment]
I guess you forked or cloned before I fixed this issue.
Check it out again 😁
