### ISSUE TITLE
LogTracer1's position

### ISSUE THREAD

**Issue by apollonian11** [parkjs814/AlgorithmVisualizer#112]
Reporting an unexpected behavior. LogTracer1 section appears above the Encryption & Decryption sections [here](http://jasonpark.me/AlgorithmVisualizer/#path=cryptography/caesar_cipher/basic) (Trace tab).

![capture](https://cloud.githubusercontent.com/assets/2150306/15634041/5b66b76e-25d8-11e6-9230-9b2ffb508acb.JPG)

**Comment by duaraghav8** [comment]
Hi,
I don't think its unexpected. The position of tracers depends upon the order in which they are created.
Have a look at Affine Cipher, and notice that, in data.js, new LogTracer () is called **after** the other tracers were created, so it comes below them in the visual.

Here, see the "Scratch Paper" section of [this](http://jasonpark.me/AlgorithmVisualizer/#path=scratch/b0c2899b09c247da4566a52c6fa319b4)

The same ceaser cipher code, but logger is created after the other tracers, so it appears below them.

Hope this clarifies

**Comment by apollonian11** [comment]
Hello Raghav,

Agreed. I expressed my doubt because the logger appears at the bottom on all pages expect the one mentioned here.

Why is this not the order?
```javascript
var encryptTracer = new Array1DTracer('Encryption');
var decryptTracer = new Array1DTracer('Decryption');
var logger = new LogTracer();
```

P.S. These pages have LogTracer on the top too: [Ugly Numbers](http://jasonpark.me/AlgorithmVisualizer/#path=dp/ugly_numbers/basic) & [Substring Search](http://jasonpark.me/AlgorithmVisualizer/#path=string/knuth_morris_pratt/substring_search)

**Comment by parkjs814** [comment]
The order of tracers will be refreshed when you cut those three lines and paste them at the same place.
I can say this is a bug.

**Comment by duaraghav8** [comment]
@apollonian11 I see your point. Best for the LogTracer to maintain consistency (in appearing at the bottom always), thanks for the re-ordering.

@parkjs814 Could you please explain why you say its a bug? If you cut those lines and paste the same back, the order remains intact. The tracers themselves are refreshed, but they still follow the order in which they are declared in the code.

**Comment by apollonian11** [comment]
@duaraghav8 #112 is solved. :+1:

**Comment by parkjs814** [comment]
@duaraghav8 
`TracerManager` saves the **types** of tracer in an array for ordering.
If the code is changed, `TracerManager` removes unused types of tracer, adds newly used types of tracer, and assigns the actual tracer objects to the DOM elements based on the array.
So when using the same types of tracer, there is no problem in ordering.

Here is the example of the case that it doesn't follow the order.

1.
```js
new DirectedGraphTracer('a');
new LogTracer('b');
new Array2DTracer('c');
```
order = [DirectedGraphTracer, LogTracer, Array2DTracer]

2.
```js
new DirectedGraphTracer('a');
new LogTracer('b');
```
order = [DirectedGraphTracer, LogTracer]

3.
```js
new Array2DTracer('c');
new DirectedGraphTracer('a');
new LogTracer('b');
```
order = [DirectedGraphTracer, LogTracer, Array2DTracer]

**Comment by duaraghav8** [comment]
Ah! I see, thanks
