### ISSUE TITLE
TypeError: indexes.forEach is not a function

### ISSUE THREAD

**Issue by yigitozkavci** [parkjs814/AlgorithmVisualizer#13]
First time I try to run "Binary Search", it gives this error: 

![image](https://cloud.githubusercontent.com/assets/7188811/15456135/1e45b7ee-2070-11e6-8cee-5ac01ea185e6.png)

**Comment by parkjs814** [comment]
I'm not sure but I was fixing something on Binary Search at that time.
Can you check if it happens again?

**Comment by yigitozkavci** [comment]
It seems fine now, closing then, thanks :)

**Comment by parkjs814** [comment]
You're welcome 👍
