### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by duaraghav8** [parkjs814/AlgorithmVisualizer#143]
The number of visualizations is growing fast. Eventually, we'll face 2 problems:

1. Users will have a tough time finding a particular visualization (and determining if it exists at all) because they may not be able to guess the right category to look under. For instance, Longest Common Subsequence could come under String as well as under DP. A smoother way would be to just type in the algorithm in search bar and poof! you have it

2. Anybody who wants to contribute a new visual will first have to determine whether a particular algo/DS already exists or not. This too becomes frustrating once we have too many visuals and no search bar to quickly filter.

I've started working on a search bar feature. [Simple](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSs3q8RDQE-oI02QE7uAe9FF0qOMUv7idd0FsAwPD5VyQ3G2K3k) looking
Opinions?

**Comment by nem035** [comment]
Yup, this is definitely needed.

**Comment by parkjs814** [comment]
That will be great.
In which are you going to add it, side menu or navigation bar?

**Comment by duaraghav8** [comment]
The nav bar seems like a better option, easily visible and we can make it quite wide. There are really good Ajax-based autocomplete plugins for search box implementation. (eg- http://www.tipue.com/drop/)

Alternatively, it could be in side menu. As soon as you start typing, the menu is replaced by clickable suggestions. Which one seems better to you?

Also, my css skills are very poor, so the UI will be minimal. I'd be grateful if others would improve it.

**Comment by nem035** [comment]
If we are keeping the sidebar to the left (and completely preloading it the way we do it now), then my vote is to put the search bar on the sidebar. I also think that since data is already preloaded, we don't need to use ajax and should just do in-memory filtering of results, no need to make network requests for things we already have.

**Comment by duaraghav8** [comment]
@nem035 Adding dropdown is one of the options I was considering. But you're right about ajax, we already have the entire list in memory, silly me!

I'm a bit more inclined toward the header search bar which will show matches from the in-memory list when the user starts typing, so I'll work on that.

Sure, thanks!
