### ISSUE TITLE
Enable Fullscreen

### ISSUE THREAD

**Issue by duaraghav8** [parkjs814/AlgorithmVisualizer#170]
I'm currently working on full screen feature, here's the demo:
http://duaraghav8.github.io/AlgorithmVisualizer

(notice the Fullscreen button next to Share button on nav bar)
The feature will work with browsers which support the Fullscreen API (I've added vendor IDs for chrome, firefox, opera, IE)
(https://github.com/duaraghav8/AlgorithmVisualizer/blob/gh-pages/js/dom/enable_fullscreen.js)

The issue is: when I change to full screen, a lot of the App's UI distorts (notice the loading bar, side menu).
**CSS needs to be written to handle elements in full screen**, but I'm not that good with it. I've written the JS part. I'm currently looking into:

https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
https://www.sitepoint.com/html5-full-screen-api/
https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen

but if anyone is willing to take up the CSS part (or help me write it), please let me know, would appreciate it:)

**Comment by parkjs814** [comment]
Great idea.
Can you create `fullscreen` branch in this repo and pull this?
I will look into it.
