### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by parkjs814** [parkjs814/AlgorithmVisualizer#176]
Due to some inconveniences of GitHub Pages including `gulp` confliction, it seems much better to deploy our repo to Heroku.
From now on, every commits pushed to `master` branch are automatically deployed to [http://algo-visualizer.jasonpark.me/](http://algo-visualizer.jasonpark.me/) or [http://algorithm-visualizer.herokuapp.com](http://algorithm-visualizer.herokuapp.com), running on `gulp`.
What I'm going to do is that after DNS server is fully refreshed, I will redirect http://jasonpark.me/AlgorithmVisualizer to http://algo-visualizer.jasonpark.me/ because CNAME alias (connection between Heroku and domain `jasonpark.me`) doesn't support subdirectory but subdomain.

@nem035 @duaraghav8 @TornjV

**Comment by gautamkrishnar** [comment]
You can also try out openshift; https://www.openshift.com/
Try applying for a free open source instance:https://www.openshift.com/grants/
