### ISSUE TITLE
gulp error

### ISSUE THREAD

**Issue by linkkingjay** [parkjs814/AlgorithmVisualizer#189]
I got this error when I ran `gulp`:
```
Error: ENOENT: no such file or directory, lstat '/Users/link/workshop/AlgorithmVisualizer/css/algorithm_visualizer.css'
```
![blob](https://cloud.githubusercontent.com/assets/12758282/16239432/6d827ce4-3802-11e6-899a-fbca37ee6f20.png)

**Comment by TornjV** [comment]
That file should be build into the public directory, not in css.
Is your local repo up to date with this one ?

**Comment by linkkingjay** [comment]
@TornjV I'm sure it is update to date.

**Comment by parkjs814** [comment]
Can you `npm update` and try `gulp` again?
There has been a [significant issue](https://github.com/tracker1/gulp-header/issues/37) in `gulp-header` module for a few days, and it seems fixed recently.

**Comment by linkkingjay** [comment]
@parkjs814 It works 👍
