### ISSUE TITLE
Multiple tracers for a single view?

### ISSUE THREAD

**Issue by duaraghav8** [parkjs814/AlgorithmVisualizer#19]
Is it possible to use more than 1 tracer for a single visualization? I'd like to use one for Directed Graph and another for 1D Array to display the progress. I tried a lot of things but it doesn't seem to be working.

Does the current implementation allow it?

**Comment by parkjs814** [comment]
I have noticed that some algorithms inevitably need more than one tracer. I am currently picturing it how I should arrange several tracers. Feel free to give me any opinions about it. Btw, thanks for your contributions :)

**Comment by duaraghav8** [comment]
Sure. I'm currently trying to understand the code base. I'd like to contribute to the re-implementation of tracers. Do share your ideas if you feel I can be of some help in it.

**Comment by parkjs814** [comment]
Let's just remain it open until finish developing multiple tracers.
Contribute to the core modules will be really appreciated. 👍
Feel free to ask if you don't get any of code pieces.

Additionally, I revised the core structure little bit so that you'd better to check it out before you work on modules.

**Comment by parkjs814** [comment]
added at 0ef789769d45b88ce6c37ca81db585f26d8a9337

**Comment by rajington** [comment]
Really nice! Whipping up something complicated to use this right now.

**Comment by rajington** [comment]
I took a stab at implementing the Slope One item-item collaborative filtering algorithm http://rajington.github.io/AlgorithmVisualizer/ based on the example at the end of the chapter here: http://guidetodatamining.com/assets/guideChapters/DataMining-ch3.pdf

**Comment by parkjs814** [comment]
@rajington looks awesome! Can you send us the pull request of it?
