### ISSUE TITLE
Possible problem while running the project locally

### ISSUE THREAD

**Issue by duaraghav8** [parkjs814/AlgorithmVisualizer#2]
I cloned the project and fired up the index.html. The environment loads, but the **Data doesn't because the browser's Cross Origin Security Policy blocks it from loading**.

So I wrote a simple Node Script which can be used as the entry point of the server instead.
So instead of launching index.html, people can launch the Script and get **http://localhost:8080**, then everything works flawlessly.
![shot](https://cloud.githubusercontent.com/assets/12758282/15452794/b79d821c-2018-11e6-8b32-7710e0473000.png)

The script (stays in the root directory) is:

**server.js** 

```
process.chdir (__dirname);

var app = require ('express') (),
	serveStatic = require ('serve-static');

app
	.use (serveStatic (__dirname))
	.listen (process.env.NODE_ENV || 8080, function () {
		console.log ('Ready');
	});
```

Do you think it will be a good idea to upload the above server.js & Package.json on this repository for the ease of others?

**Comment by parkjs814** [comment]
Oops I had never tested locally on Chrome.
Thank you for reporting this significant issue.
I guess it looks weird if I add Node.js files into this repo.
Instead, I found a proper repo behaving in the same way as you suggest.
I will notice this in README.md.

**Comment by duaraghav8** [comment]
You're welcome:)
Ah! I agree, the http-server utility is a more sensible solution.

**Comment by parkjs814** [comment]
Check out the new README.md 👍
