### ISSUE TITLE
Add rich preview image when sharing the website on services like Slack, Whatsapp, etc.

### ISSUE THREAD

**Issue by gianpaj** [parkjs814/AlgorithmVisualizer#24]
Info about Open Graph:
- https://get.slack.help/hc/en-us/articles/204399343-Sharing-links-in-Slack
- https://developers.facebook.com/docs/sharing/best-practices#images

Test with this URL:
http://richpreview.com/?url=http://jasonpark.me/AlgorithmVisualizer/

I'm happy to do a pull request once you tell me what image should be used. Apparently some services  even support gif, which might be useful to explain how the site works.

**Comment by parkjs814** [comment]
Good idea, I think we can just use a screenshot of the webpage (without the frame of the browser) as the image. Your pull request will be appreciated 👍
