### ISSUE TITLE
Feature request: Save custom algorithms / scratch papers with unique urls for ease of sharing

### ISSUE THREAD

**Issue by gianpaj** [parkjs814/AlgorithmVisualizer#25]

**Comment by parkjs814** [comment]
I have thought about it, and I'm still planning how I should do this within a static page.

**Comment by parkjs814** [comment]
I may be able to use apis of Pastbin.com to save and load scratch papers. Thanks for reminding me!

**Comment by parkjs814** [comment]
added at f148adb9014865569f0a359484059f458475a06c
