### ISSUE TITLE
Dynamic loading of nodes in the visualization

### ISSUE THREAD

**Issue by duaraghav8** [parkjs814/AlgorithmVisualizer#26]
An appropriate visualization for recursive algorithms would be to show the Recursion Tree **as it develops**. A good feature provided by tracer would be to allow the adding of more Nodes in the graph, which are then also added on to the screen **during Run time.**

Another feature could be to display custom text in the Nodes instead of the default numbers representing them.
Something like:

`
G.push ([1, 1, 0, 1]);  //also, edit the rest of the Graph to accommodate 1 more Node
tracer._updateGraph (G);  //this updates the visualization to contain the new Node(s)
`

`
var labels = {0: "Node #0", 3: "Node #3"}; 
`
` //labels for all the nodes, labels for Node 1 & 2 remain the default ones`
`
tracer._updateLabels (labels);
`

**Comment by parkjs814** [comment]
👍 That will be useful. I will see after implementing multiple tracer stuff. (It seems take some time.)

**Comment by parkjs814** [comment]
added at fd16e475474eb5a136b438388de2c2acba74078b
