### ISSUE TITLE
Need Scrolling feature for Files Bar

### ISSUE THREAD

**Issue by duaraghav8** [parkjs814/AlgorithmVisualizer#55]
Under Dynamic Programming under Uncategorized, the **max_subarray** tab is not visible. If we stretch the Editor left a little bit, it becomes visible.
This becomes a problem when a category has more than a few programs. Their tabs get hidden.

We therefore need a way to notify the user that there may be more tabs to the right, which are hidden.
A suitable way would be to give a scrolling feature so the user knows that they can scroll to the right and see more visualizations under that category.

**Comment by duaraghav8** [comment]
@parkjs814 here's a screenshot of what I've implemented. (Notice the Next & Previous Button)
If you think it looks fine, I'll merge.

![shot](https://cloud.githubusercontent.com/assets/12758282/15545253/4d36d2a4-22b9-11e6-9f54-ab0a20abd489.png)

**Comment by TornjV** [comment]
I would try something like this and without text.
http://jsfiddle.net/f4xkxkwL/

**Comment by TornjV** [comment]
Or, since we seem to use font-awesome and not bootstrap atm, maybe just use one of these.
http://fontawesome.io/icons/

**Comment by duaraghav8** [comment]
@TornjV  Well, icons alone are quite intuitive. So I guess they're suitable as well

**Comment by parkjs814** [comment]
@duaraghav8 It looks great.
As @TornjV it will be okay without text.

**Comment by parkjs814** [comment]
I've thought about it more, and we may need to show the lists vertically somewhere since they are going to be too many. How do you guys think?

**Comment by archie94** [comment]
Additionally I think there should be a horizontal scroll for the algorithm description bar. For a large description like in the Knapsack Problem, it is becoming difficult to read.

**Comment by duaraghav8** [comment]
guys please test [my fork](https://github.com/duaraghav8/AlgorithmVisualizer) on your machines for the scrolling in Files Bar
Don't pay attention to the icons, will change them.
Just see if the functionality is good enough, or does something need to be changed.
Thanks

**Comment by parkjs814** [comment]
@duaraghav8 can you push it to gh-pages so that everyone can see easily?

**Comment by duaraghav8** [comment]
I don't have a problem with that. I just didn't want to push it until it was finalized. I'll do it, just check and let me know.

**Comment by duaraghav8** [comment]
Ok done, check

**Comment by parkjs814** [comment]
I meant push it to `gh-pages` on your fork, my bad.
But no worries, it looks great :)

**Comment by archie94** [comment]
:+1:  Is it possible to grey out the next button to indicate the end of the list ? 

Great work with the description bar  :+1:

**Comment by duaraghav8** [comment]
@archie94 I thought about it too. I first wanted people to decide if this looks ok. I'll improve it further, thanks

**Comment by parkjs814** [comment]
@duaraghav8 I'm currently working on improving it. I'll let you know when I'm done.

**Comment by parkjs814** [comment]
improved at 99c5a3eeb244c25f58070b6ff720d57a8d67bdbc
