### ISSUE TITLE
Non-naive bridge finding

### ISSUE THREAD

**Issue by PFischbeck** [parkjs814/AlgorithmVisualizer#58]
When I saw the naive bridge finding algorithm (PR #54), I expected a non-naive version as well.
There is a version by Tarjan (https://en.wikipedia.org/wiki/Bridge_%28graph_theory%29#Tarjan.27s_Bridge-finding_algorithm).
There is also an easier version on the internet (http://stackoverflow.com/a/28917697/262526), but unfortunately I was unable to find the original source for this.

Anyone willing to implement this?

**Comment by duaraghav8** [comment]
@PFischbeck When I implemented the Naive one I had the exact same though. I'm currently working on another issue, but once I find time I'll also implement Tarjan's. But if anyone else is willing to contribute, that too would be great!

**Comment by duaraghav8** [comment]
@PFischbeck I've added the O(V+E) algorithm. I'm open to feedback.
