### ISSUE TITLE
Chart tracer

### ISSUE THREAD

**Issue by TornjV** [parkjs814/AlgorithmVisualizer#71]
![screen shot 2016-05-26 at 4 48 22 pm](https://cloud.githubusercontent.com/assets/13820300/15578661/ae640d0a-2361-11e6-8038-423714c9ce37.png)
Would this kind of tracer be useful?
Uses [Chart.js](http://www.chartjs.org/)

**Comment by parkjs814** [comment]
It will definitely be useful!
We can add this tracer to most of the sorting algorithms!
👍

**Comment by parkjs814** [comment]
Have you already implemented? or is it just mockup?

**Comment by TornjV** [comment]
#91
