### ISSUE TITLE
Visual Array Dividers

### ISSUE THREAD

**Issue by pheintzelman** [parkjs814/AlgorithmVisualizer#79]
For algorithms like merge and quick sort a visual indicator of a divide would be nice.

very quick version:
 
![image](https://cloud.githubusercontent.com/assets/2145906/15590236/7768b2bc-234b-11e6-8fa3-d9db8653b26c.png)

I think just a gap or a black line. Only chose red in my picture to be clear.

**Comment by parkjs814** [comment]
How creative! I will work on it soon :)

**Comment by parkjs814** [comment]
Mhm this is creative! I will work on it soon.

**Comment by parkjs814** [comment]
added at fa78c4c97e3a3abf8285491a89e907da728da0b2

Check out the [example](http://jasonpark.me/AlgorithmVisualizer/?scratch-paper=2d2a9478613017d354b55ef8741d955f)!
