### ISSUE TITLE
Bottom Up Merge

### ISSUE THREAD

**Issue by bbarry** [parkjs814/AlgorithmVisualizer#88]
The existing merge implementation is overly complex and doesn't show what it is doing very well. I suggest exposing the internal working arrays and switching to a non-recursive bottom up implementation:

https://gist.github.com/bbarry/020db3f362cd410958fab7b7891bdd16

**Comment by parkjs814** [comment]
Look does look much easier to understand! I will add it to merge sort.

**Comment by parkjs814** [comment]
added at 1db8388729045d109dbedb6ac1a767f728dc1b32
